"""init: create tokens, admin_config, media tables

Revision ID: 260572e0c2da
Revises: 
Create Date: 2026-03-03 23:06:09.878846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260572e0c2da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_config',
    sa.Column('key', sa.String(length=64), nullable=False, comment='配置键名，如 password_salt、password_hash'),
    sa.Column('value', sa.Text(), nullable=False, comment='配置值，存储对应键的具体内容'),
    sa.PrimaryKeyConstraint('key'),
    comment='管理后台配置表，存储管理员密码哈希等系统配置'
    )
    op.create_table('media',
    sa.Column('media_id', sa.String(length=64), nullable=False, comment='媒体文件唯一标识，media_ 前缀 + UUID hex'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名（已做路径遍历安全处理）'),
    sa.Column('mime_type', sa.String(length=128), nullable=False, comment='MIME 类型，如 image/png、application/pdf'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小（字节），最大 50MB'),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False, comment='上传者的令牌值，关联 tokens.token'),
    sa.Column('uploaded_at', sa.Double(), nullable=False, comment='上传时间，Unix 时间戳（秒）'),
    sa.Column('expires_at', sa.Double(), nullable=False, comment='过期时间，Unix 时间戳（秒），默认上传后 7 天'),
    sa.PrimaryKeyConstraint('media_id'),
    comment='媒体文件元数据表，记录上传文件的信息，实际文件存储在本地文件系统'
    )
    op.create_index('idx_media_expires_at', 'media', ['expires_at'], unique=False)
    op.create_index('idx_media_uploaded_by', 'media', ['uploaded_by'], unique=False)
    op.create_table('tokens',
    sa.Column('token', sa.String(length=64), nullable=False, comment='令牌值，sk- 前缀 + 24字节hex，全局唯一标识'),
    sa.Column('created_at', sa.Double(), nullable=False, comment='创建时间，Unix 时间戳（秒）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='令牌名称，便于管理员识别用途'),
    sa.Column('expires_at', sa.Double(), nullable=False, comment='过期时间，Unix 时间戳（秒），9999999999.0 表示永不过期'),
    sa.PrimaryKeyConstraint('token'),
    comment='API 访问令牌表，管理 bot 和 chat 客户端的接入凭证'
    )
    op.create_index('idx_tokens_expires_at', 'tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tokens_expires_at', table_name='tokens')
    op.drop_table('tokens')
    op.drop_index('idx_media_uploaded_by', table_name='media')
    op.drop_index('idx_media_expires_at', table_name='media')
    op.drop_table('media')
    op.drop_table('admin_config')
    # ### end Alembic commands ###
